# -*- coding: utf-8 -*-
"""weather forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e6UX98w3LDfU2FWJJw3z-JRSuzK6-uJs
"""

import pandas as pd

dataframe=pd.read_csv('/file.csv')

dataframe

"""# **Unique Data of weather**"""

dataframe['Weather'].unique()

"""# **Find the number of times when the 'Weather is exactly Clear'**"""

dataframe['Weather'].value_counts()["Clear"]

dataframe['Weather']

"""# **Find the number of times when the 'Wind Speed was exactly 4 km/h'.**"""

dataframe['Weather'].value_counts()[4]

"""# **Find out all the Null Values in the data.**"""

dataframe.isnull().sum()

dataframe

"""# **Rename the column name 'Weather' of the dataframe to 'Weather Condition'.**"""

dataframe.rename(columns={'Weather' : 'Weather Condition'}, inplace=True)

dataframe

"""# **What is the mean 'Visibility' ?**"""

dataframe['Visibility_km'].describe()

"""# **What is the Standard Deviation of 'Pressure'  in this data?**"""

dataframe['Press_kPa'].describe()

"""# **Q. 8) What is the Variance of 'Relative Humidity' in this data ?**

"""

dataframe['Rel Hum_%'].var()

"""# **Q. 9) Find all instances when 'Snow' was recorded.**

"""

dataframe['Weather Condition'].value_counts()["Snow"]

"""# **Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.**



"""

dataframe[(dataframe['Wind Speed_km/h']>24 )& (dataframe['Visibility_km']==25)]

"""# **12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?**"""

dataframe['Weather Condition'].describe()

"""# **13) Show all the Records where Weather Condition is Fog.**"""

dataframe[(dataframe['Weather Condition']=="Fog" )]

"""# **14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.**"""

dataframe[(dataframe['Weather Condition']=="Clear" )| (dataframe['Visibility_km']>40)]

"""**# 15) Find all instances when : A. 'Weather is Clear' and 'Relative Humidity is greater than 50' or B. 'Visibility is above 40'**"""

dataframe[((dataframe['Weather Condition']=="Clear" ) & (dataframe['Rel Hum_%']>50)) | (dataframe['Visibility_km']>40)]